import * as XLSX from "xlsx";
import { PDFDocument, StandardFonts } from "pdf-lib";

const base = process.env.APP_BASE_URL || "http://localhost:3000";
let cookie = "";
async function call(path, method = "GET", data) {
  const response = await fetch(base + path, { method, headers: { ...(cookie ? { Cookie: cookie } : {}), ...(method !== "GET" ? { Origin: base, "Content-Type": "application/json" } : {}) }, body: data ? JSON.stringify(data) : undefined });
  if (response.headers.get("set-cookie")) cookie = response.headers.get("set-cookie").split(";")[0];
  const body = await response.json();
  if (!response.ok) throw new Error(`${path}: ${response.status} ${body.error || ""}`);
  return body;
}
const health = await call("/api/health");
if (health.catalog.mode !== "demo") throw new Error("Smoke script is for demo mode only.");
const search = await call("/api/products/search?q=DEMO-AV16");
if (!search.items.some(item => item.id === 1001)) throw new Error("Search failed");
const chat = await call("/api/chat", "POST", { message: "DEMO-AV16" });
if (chat.products?.[0]?.id !== 1001) throw new Error("Chat lookup failed");
const history = await call("/api/chat");
if (!history.messages?.some(message => message.role === "user" && message.content === "DEMO-AV16")) throw new Error("Chat history failed");
const before = await call("/api/cart");
const proposal = await call("/api/cart/proposals", "POST", { lines: [{ productId: 1001, quantity: 2 }] });
const pending = await call("/api/chat");
if (pending.pendingProposal?.id !== proposal.id) throw new Error("Pending proposal was not restored");
const unchanged = await call("/api/cart");
if (before.lines.length || unchanged.lines.length) throw new Error("Cart changed before confirmation");
const result = await call("/api/cart/confirm", "POST", { id: proposal.id, version: proposal.version });
const repeat = await call("/api/cart/confirm", "POST", { id: proposal.id, version: proposal.version });
const after = await call("/api/cart");
if (result.cartUrl !== "/cart" || after.lines[0]?.quantity !== 2 || !repeat.repeated) throw new Error("Confirmation failed");
const updated = await call("/api/cart", "PATCH", { key: after.lines[0].key, version: after.version, quantity: 3 });
if (updated.lines[0]?.quantity !== 3) throw new Error("Cart update failed");
const workbook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet([["DEMO-AV16", 1, "шт"]]), "Заказ");
const form = new FormData();
form.append("file", new Blob([XLSX.write(workbook, { type: "buffer", bookType: "xlsx" })], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), "spec.xlsx");
const uploadResponse = await fetch(base + "/api/uploads", { method: "POST", headers: { Cookie: cookie, Origin: base }, body: form });
const upload = await uploadResponse.json();
if (!uploadResponse.ok || upload.rows?.[0]?.productId !== 1001) throw new Error(`Upload failed: ${upload.error || "wrong match"}`);
const pdf = await PDFDocument.create();
const pdfPage = pdf.addPage([400, 200]);
pdfPage.drawText("DEMO-AV16 1", { x: 30, y: 150, font: await pdf.embedFont(StandardFonts.Helvetica), size: 16 });
const pdfForm = new FormData();
pdfForm.append("file", new Blob([await pdf.save()], { type: "application/pdf" }), "spec.pdf");
const pdfResponse = await fetch(base + "/api/uploads", { method: "POST", headers: { Cookie: cookie, Origin: base }, body: pdfForm });
const pdfResult = await pdfResponse.json();
if (!pdfResponse.ok || pdfResult.rows?.[0]?.productId !== 1001) throw new Error(`PDF upload failed: ${pdfResult.error || "wrong match"}`);
const removed = await call("/api/cart", "DELETE", { key: after.lines[0].key, version: updated.version });
if (removed.lines.length) throw new Error("Cart removal failed");
console.log("HTTP smoke passed: search, chat, proposal, confirmation, idempotency, cart edits, XLSX/PDF upload. Session cookie:", Boolean(cookie));
